### PR TITLE
FEAT: Add falco and multiqc.

### PR DESCRIPTION
**Pull request by DriesSchaumont**

### CODE REVIEW

**Comment by tverbeiren** [comment]
I suggest to split the two blocks of groovy code off in two separate workflows, something like `split_samples_and_validate` and `combine_samples`.

**Comment by DriesSchaumont** [comment]
> I suggest to split the two blocks of groovy code off in two separate workflows, something like `split_samples_and_validate` and `combine_samples`.

Done! I also added multiqc in the meantime ⏩

**Comment by tverbeiren** [comment]
Looks good!

My suggestion would be to put the spun off workflows in their separate 'component' like for instance https://viash-hub.com/data-intuitive/vsh-pipeline-operators/-/tree/main/src/split/vsh_flatten?ref_type=heads.

**Comment by DriesSchaumont** [comment]
> Looks good!
> 
> My suggestion would be to put the spun off workflows in their separate 'component' like for instance https://viash-hub.com/data-intuitive/vsh-pipeline-operators/-/tree/main/src/split/vsh_flatten?ref_type=heads.

I'm not sure that the current workflow got simpler by doing this. But once more functionality is added I think it will have been beneficial ✅

**Comment by tverbeiren** [comment]
Looks good!

**Review by tverbeiren — APPROVED** [review]

**Pull request merged**
